---
- name: Add MariaDB repo
  template: src=yum.repos.d/mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo
    owner=root group=root mode=0644
 
- name: Disable Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
    
- name: Disable SELINUX
  selinux:
    state: disabled
  register: selinux
  
#- name: restart machine
#  shell: /bin/sleep 5 && shutdown -r now "ansible restart"
#  ignore_errors: true
#  when: selinux.changed

- name: Crea directory per mount mysql data
  file:
    path: "{{ item }}"
    owner: mysql
    group: mysql
    mode: 0755
    state: directory
  with_items:
    - /pluto
    - /pluto/paperino
  
# Reboot
- name: (reboot) Reboot triggered
  command: /sbin/shutdown -r +1 "Ansible-triggered Reboot"
  async: 0
  poll: 0

- name: (reboot) Wait for server to restart
  wait_for_connection:
    delay: 75
  
