- name: Create partition for LVM
  parted:
    device: "/dev/{{datadev_name}}"
    number: 1
    flags: [ lvm ]
    state: present
    part_start: 0%
    part_end: 100%
  register: lvm_format

- name: Create volume group
  lvg:
    vg: vg_mysql
    pvs: "/dev/{{datadev_name}}1"
    state: present
  when: lvm_format|succeeded
  register: vg_create

- name: Create logical volume
  lvol:
    vg: vg_mysql
    lv: lv_mysql
    size: 100%VG
    active: yes
    state: present
  when: vg_create|succeeded
  register: lv_create

- name: Format volume with XFS
  filesystem: 
    fstype: xfs 
    dev: /dev/vg_mysql/lv_mysql
  when: lv_create|succeeded
  register: xfs_format

- name: Crea directory per mount mysql data
  file:
    path: "{{mysql_dir}}"
    state: directory
    owner: mysql
    group: mysql
  
- name: Edit fstab and mount the XFS volume
  mount:
    name: "{{mysql_dir}}"
    src: /dev/vg_mysql/lv_mysql
    fstype: xfs
    opts: "noatime"
    state: mounted
