---
- name: Modifca data directory
  shell: /usr/lib/mysql_install_db --user=mysql --datadir="{{mysql_dir}}" --skip-name-resolve

- name: Ensure MariaDB is running
  service: name=mariadb state=started

#- name: Add Galera SST user
#  mysql_user: name={{ galera_sst_user }} host="{{ item }}"
#    password={{ galera_sst_pass }} priv="*.*:ALL" append_privs=yes
#  with_items:
#    - "localhost"
